# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Andaze Hugo Amp"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = ""
homepage = "https://www.andaze.com/ja/dynamics365"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Andaze"
  homepage = "https://www.andaze.com/"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
