# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Andaze Hugo Amp"
license = "MIT"
licenselink = "https://github.com/andaze/andaze-hugo-amp/blob/master/LICENSE"
description = "An AMP pages supported Hugo theme for technical documentation sites."
homepage = "https://www.andaze.com/ja/dynamics365"
tags = ["AMP","documentation","multilingual","responsive","docs"]
features = []
min_version = "0.41.0"

[author]
  name = "Andaze"
  homepage = "https://www.andaze.com/"